apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: r1xth4n2i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: r1xth4n2i-go 
  name: r1xth4n2i-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: r1xth4n2i-go 
